export const CSS_HANDLES = [
  'containerOffer',
  'containerTitleAndSeeMore',
  'bannerOffer',
  'containerProductOffer',
  'containerCountdown',
  'shelfContainer',
  'subtitle',
  'seeMore',
  "contentTitle",
  'contentWrapper',
  'countdownText',
  'countdownStrong',
  'countdown',
  'offer-wrapper',
  'icon-container',
  'icon',
  'offer-content',
  'title-container',
  'title',
  'time-container',
  'days',
  'days-id',
  'hours',
  'minutes',
  'seconds',
] as const
