export const faker = [
  'Lyor Classic',
  'Nike',
  'Jd Molina',
  'Poquema',
  'Permóbili',
  'Móveis Europa',
  'Colibri',
  'Móveis Albatroz',
  'Mgm',
  'Cimol',
  'Poliman',
  'Made Marcs',
  'Politorno',
  'Artely',
  'Móveis Primus',
  'Novo Horizonte',
  'Docelar',
  'VLGL Estofados',
  'Nova Mobile',
  'GenialFlex',
  'Alegro',
  'Henn',
  'Diamante',
  'Placa e Ponto',
  'Acp Móveis',
  'Dobue',
  'Havana',
  'Rivatti',
  'Fellicci',
  'Or Design',
  'Castro',
  'House',
  'Móveis Belini',
  'Zanzini',
  'Appunto',
  'Royal',
  'Volttoni',
  'Tecno Mobili',
  'Linoforte',
  'Evolux',
  'Cewal Móveis',
  'Imaza Móveis',
  'Nesher',
  'Completa Móveis',
  'Miralupa',
  'EDN Móveis',
  'Casa de Pedra',
  'Pelmex',
  'Carioca Móveis',
  'Flash Limp',
  'Artany',
  'Oex',
  'Caemmun',
  'Tebarrot',
  'Matrix',
  'Gourmet Mix',
  'Paramount',
  'Termopro Glass',
  'Alleanza',
  'BRV',
  'Maria Móveis',
  'Le Cook',
  'Domi Móveis',
  'Dazz',
  'Santos Andirá',
  'Prodormir',
  'Angels Design e Art',
  'J.Serrano',
  'Serpil',
  'KOS',
  'Phoenix Puff',
  'MultiMóveis',
  'Urban',
  'Belmax',
  'Quiditá',
  'Premium Estofados',
  'Carolina Baby',
  'Gigapro',
  'Armazem da Mobilia',
  'Clean Gel Plus',
  'Rodial',
  'Edumax',
  'Olivar',
  'D Angelis',
  'Móveis Estrela',
  'Rufato',
  'Mobisul',
  'Estilare',
  'Lightspuma',
  'Combinare',
  'Móveis Clement',
  'Mondoceram Gourmet',
  'Sleep  Design',
  'Ventidelta',
  'Electrolux',
  'Rayza',
  'Euro Home',
  'Euro Home',
  'Samsung',
  'Crisa',
  'Simbal',
  'Nadir',
  'Bon Gourmet',
  'Ceraflame',
  'Charlie Pet',
  'Agratto',
  'Keter',
  'Lg',
  'Porto Brasil',
  'Ventisol',
  'Curty',
  'Arthi',
  'Burigotto',
  'Ricaelle',
  'Maria Lua Baby',
  'Schmidt',
  'Tutti Baby',
  'Wolff',
  'Marilena G',
  'Metal do Brasil',
  'Metávila',
  'Edantex',
  'Hellen',
  'Alves Pereira',
  'Future',
  'Corttex',
  'Açomix',
  'Forma Inox',
  'Percasa',
  'Tapetes São Carlos',
  'Primatto',
  'Dolce Vita',
  'Papaiz',
  'Artesanal Teares',
  'Juma',
  'Yale',
  'Art In Móveis',
  'Kapos',
  'Gw',
  'Belchior',
  'Kikos',
  'Oxford',
  'Plasútil',
  'Cortbras',
  'Madetec',
  'Anc Estofados',
  'Lancer',
  'Mobler',
  'Bechara',
  'Tiny Love',
  'Termopro',
  'Gasil',
  'Mart',
  'Startec',
  'Prorelax',
  'Legacy Sofás',
  'Nacional',
  'Teka',
  'Arteban',
  'Bandeirante',
  'Santos Dumont',
  'Barella Flex',
  'Azmax',
  'Black e Decker',
  'Daf Mobiliário',
  'Phormatta',
  'Panelux',
  'Taschibra',
  'Elgin',
  'Empório Tiffany',
  'Batistela Baby',
  'Becadecor',
  'RV Móveis',
  'Sofá Home',
  'SalehTex',
  'Divicar',
  'Eucamóveis',
  'Luciane',
  'Fritz Móveis',
  'Conquista',
  'Notável',
  'DJ',
  'Sir',
  'Gelius',
  'Plumatex',
  'Móveis Canção',
  'Celuplás',
  'Herval Madeiras',
  'Cambel',
  'Moval',
  'Herval',
  'Pura Magia',
  'Paropas',
  'Araplac',
  'Solar',
  'Kits Paraná',
  'Mobilare',
  'Ecomóveis',
  'Carraro Cozinhas',
  'Epeda',
  'Modecor',
  'Canaã',
  'Ideia Vidros',
  'Sademi',
  'Quarta Divisão',
  'Design Final',
  'Estrela',
  'AmericanFlex',
  'CCL',
  'Linea Brasil',
  'Travel Max',
  'Fibrasca',
  'Kacyumara',
  'Santista',
  'Artex',
  'Camesa',
  'Acaz',
  'Dalla Costa',
  'Bom Lar',
  'Madesa',
  'Líder Design',
  'Ortobom',
  'Aroma Cozinhas',
  'Briz',
  'Robel',
  'Hercules',
  'Tramontina',
  'Casambiente',
  'Mundial',
  'Niazitex',
  'Soluzione',
  'Richwell',
  'Colormaq',
  'Woodart',
  'Rojemac',
  'Prestige',
  'Probel',
  'Decorine',
  'Spazzio Nobre',
  'Libell',
  'Kappesberg',
  'Bohemia',
  'Lyor Design',
  'Prana',
  'Belo Inox',
  'Dekor Cam',
  'Gelopar',
  'Dello',
  'Houston',
  'Inducol',
  'Mappin',
  'Andreza Enxovais',
  'Karsten',
  'Asiatex',
  'Loani',
  'Gazin',
  'Lynel',
  'Dohler',
  'Anjos',
  'Ambiente Móveis',
  'Golden Estofados',
  'Stay Puff',
  'Dzieco',
  'Alumínio Oliveira',
  'Galzerano',
  'Portallar',
  'Lepper',
  'AMZ',
  'Ruvolo',
  'Hecol',
  'Fitmobel',
  'Hb Móveis',
  'Belager',
  'Ciplafe',
  'Karcher',
  'Unimovel',
  'Brastubo',
  'Infanti',
  'Voyage',
  'Cosco',
  'Tcil',
  'Toalhas Atlântica',
  'Dolce Home',
  'Móveis Lanza',
  'Biona Cerâmica',
  'Kapazi',
  'D’Angellis',
  'Perfil Matelados',
  'KNR móveis',
  'Pulse',
  'Movelbento',
  'Monte Carlo',
  'Giga',
  'Bormioli Rocco',
  'Bob Burnquist',
  'Globimport',
  'Libbey',
  'Pulsesound',
  'Mondoceram',
  'Atrio',
  'Germer',
  'Bettanin',
  'Multikids',
  'Be mobiliário',
  'Multikids Baby',
  'Máxima',
  'Pozza',
  'Warrior',
  'Marinex',
  'Multilaser',
  'Duralex',
  'Weego',
  'Altenburg',
  'Marka Móveis',
  'Class Home',
  'Marka Têxtil',
  'Carraro',
  'Dinox',
  'Mão e Formão',
  'Master Comfort',
  'Kappesberg Pop',
  'Artefamol',
  'Xplast',
  'Maxi Cosi',
  'Oficina Barnello',
  'Safety  1St',
  'Itatiaia Madeira',
  'Brinox',
  'Crystalite Bohemia',
  'Visão Móveis',
  'Carolina',
  'Essenzialle',
  'Itatiaia',
  'Casamia',
  'Comfortmais',
  'Tremarin',
  'Masterkap',
  'Scalla',
  'Colorex',
  'Artefama',
  'Castor',
  'Henn Quarto',
]

export const faker2 = [
  'Artely',
  'Alumínio Oliveira',
  'AmericanFlex',
  'Anjos',
  'Artefama',
  'blu',
  'Brinox',
  'Briz',
  'Bexiga',
  'Bob Burnquist',
  'Canaã',
  'Carraro',
  'CCL',
]
