mutation($orderformID:ID, $text:String){
    insertCoupon(orderFormId:$orderformID, text:$text)
    @context(provider: "vtex.checkout-graphql")
    {
        marketingData{
            coupon
            marketingTags
            utmCampaign
            utmMedium
            utmSource
            utmiCampaign
            utmiPage
            utmiPart
        }
    }
}
