query getProductVariationsQuery($referenceId: String!) {
  products(from: 0, to: 49, query: $referenceId) @context(provider: "vtex.search-graphql") {
    productId
    link
    productName
    productReference
    items {
      itemId
      images {
        imageUrl
        imageText
      }
      variations {
        name
        values
      }
      sellers {
        commertialOffer {
          AvailableQuantity
        }
      }
    }
  }
}
